### ISSUE TITLE
deprecated method ViewModelProviders.of(this) in Mars Real Estate- Starter

### ISSUE THREAD

**Issue by Unicorn-Sol** [google-developer-training/android-kotlin-fundamentals-starter-apps#39] opened 2020-09-02 20:07 UTC
Mars Real Estate- Starter has deprecated method to initialize view model

**Comment by TheCodingArcher** [comment] 2020-09-08 08:35
Duplicate of #24

**Comment by jtavva** [comment] 2020-09-10 21:17
This issue should be fixed now. 
Please check the pull request: https://github.com/google-developer-training/android-kotlin-fundamentals-starter-apps/pull/28

Thank you for reaching out to us.

**Closed by jtavva** 2020-09-10 21:17 UTC
Labels: duplicate
